package com.progresslab.progresslab.model;


import java.time.LocalDateTime;

import org.springframework.cglib.core.Local;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/*
 *USER ENTITY
 *
 * When Spring Boot starts:
 * 1. Spring/JPA scans the application classes.
 * 2. Hibernate finds the @Entity annotation on the User class.
 * 3. Hibernate creates a table named "user" in the database with columns corresponding to the fields in the User class.
 * 4. The @Id annotation marks the id field as the primary key. 
 * 5. The @GeneratedValue annotation with strategy = GenerationType.IDENTITY indicates that the id will be auto-generated by the database.
 * 6. because ddl-auto=upddate is enabled in application.properties, Hibernate will automatically create the table if it doesn't exist or update it if the schema has changed.
 * 
 * 
 * Later:
 * 1. User Objects will represent individual records in the "user" table.
 * 2. Repository/service/controller layers will work with these objects.
*/

@Entity
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
     /*
     * User's first name.
     *
     * @NotBlank:
     * Application validation rejects null, empty, or whitespace-only values.
     *
     * nullable = false:
     * MySQL also refuses NULL for this column.
     */

    @NotBlank
    @Column(nullable = false)
    private String firstName;

    @NotBlank
    @Column(nullable = false)
    private String lastName;
     /*
     * Email is used as an account identifier.
     *
     * @Email:
     * Checks whether the input resembles a valid email.
     *
     * unique = true:
     * Database-level protection against duplicate emails.
     *
     * The service layer will also normalize/check the email before saving.
     */
    @NotBlank
    @Email
    @Column(nullable = false, unique = true)
    private String email;

    /*
     * The user initially provides a normal password.
     *
     * Validation happens before saving.
     *
     * IMPORTANT:
     * We do NOT want the plain password stored in MySQL.
     * UserService will replace it with a BCrypt hash before save().
     */

    @NotBlank
    @Size(min = 10)
    @Pattern
    (
    regexp = "^(?=.*[A-Z])(?=.*\\d)(?=.*[^A-Za-z0-9]).+$"
   )
    @Column(nullable = false)
    private String password;
    

     /*
     * Records when the User object/account was created.
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;
    
    private String resetToken;

    public void setResetToken(String resetToken)
    {
        this.resetToken = resetToken;
    }
    public String getResetToken()
    {
        return resetToken;
    }

    private LocalDateTime resetTokenExpiry;

    public LocalDateTime getResetTokenExpiry()
    {
        return resetTokenExpiry;
    }

    public void setResetTokenExpiry(LocalDateTime resetTokenExpiry)
    {
        this.resetTokenExpiry = resetTokenExpiry;
    }


    // No-argument constructor
    public User() {
    }


    // Constructor used when creating a user
    /*
     * Application constructor.
     *
     * Used when creating a brand-new User.
     *
     * We do not accept an ID because MySQL generates it.
     * createdAt is generated automatically.
     */
    public User(String firstName, String lastName,
                String email, String password)
     {

        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
        this.createdAt = LocalDateTime.now(); // Set createdAt to the current time
    }

      // Getter: allows other code to read the generated database ID.
    // No setter because normal application code should not choose the ID.
    public Long getId() {
        return id;
    }

      // Getters read values from this User object.
    // Setters allow selected values to be changed.
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
        // createdAt can be read but not normally changed.
    public LocalDateTime getCreatedAt() {
    return createdAt;
}
}
